//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prakashcrud.db_prakash
{
    using System;
    using System.Collections.Generic;
    
    public partial class empdetail
    {
        public int emp_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
    }
}
